import { Word } from "./types";

export const INITIAL_WORDS: Word[] = [
  // Beginner
  {
    id: "w1",
    word: "Abundant",
    wordClass: "Adjective",
    phonetic: "/əˈbʌndənt/",
    translation: "อุดมสมบูรณ์, มากมาย",
    definitionEn: "Existing or available in large quantities; overflowing.",
    definitionTh: "ที่มีอยู่หรือหาได้ในปริมาณมาก, เหลือเฟือ, อุดมสมบูรณ์",
    exampleEn:
      "The country has abundant natural resources such as coal and oil.",
    exampleTh:
      "ประเทศนี้มีทรัพยากรธรรมชาติที่อุดมสมบูรณ์ เช่น ถ่านหินและน้ำมัน",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story:
        'ลองจำว่า "อะ-บัน-ดันท์" -> คำว่า "บัน" (Bun = ขนมปัง) มีสะสมอยู่มากมายจน "ดัน" ล้นตู้โชว์ แปลว่า อุดมสมบูรณ์!',
      keyword: "Bun (ขนมปัง) + ดัน (ทะลัก)",
    },
  },
  {
    id: "w2",
    word: "Acquire",
    wordClass: "Verb",
    phonetic: "/əˈkwaɪər/",
    translation: "ได้รับมา, ได้เรียนรู้",
    definitionEn:
      "Buy or obtain an asset or object for oneself; learn a skill.",
    definitionTh:
      "ซื้อหรือได้รับสิ่งสินทรัพย์หรือวัตถุมาเป็นของตนเอง หรือเรียนรู้ทักษะ",
    exampleEn:
      "She managed to acquire a good knowledge of English in just six months.",
    exampleTh:
      "เธอสามารถเรียนรู้และได้รับความรู้ภาษาอังกฤษที่ดีในเวลาเพียงหกเดือน",
    difficulty: "Intermediate",
    category: "Academic",
    mnemonic: {
      story:
        'จำเสียง คล้าย "อะ-ควาย-เออร์" -> "ควาย" พยายามขยันจนในที่สุดก็ "ได้รับความรู้" (Acquire)',
      keyword: "ควายขยัน",
    },
  },
  {
    id: "w3",
    word: "Collaborate",
    wordClass: "Verb",
    phonetic: "/kəˈlæbəreɪt/",
    translation: "ร่วมมือกัน, ทำงานร่วมกัน",
    definitionEn:
      "Work jointly on an activity or project, especially to produce or create something.",
    definitionTh:
      "ทำงานร่วมกันในกิจกรรมหรือโครงการ โดยเฉพาะอย่างยิ่งเพื่อผลิตหรือสร้างสรรค์สิ่งใดสิ่งหนึ่ง",
    exampleEn:
      "Researchers from several countries collaborate on this medical project.",
    exampleTh: "นักวิจัยจากหลายประเทศร่วมมือกันในโครงการทางการแพทย์นี้",
    difficulty: "Intermediate",
    category: "Business",
    mnemonic: {
      story:
        'เสียงคล้าย "คอ-แล็บ-บอ-เรต" -> ไปนอนทำแล็บ (Lab) ด้วยกัน เพื่อ "ทำงานร่วมกัน"',
      keyword: "Lab (ห้องแล็บ)",
    },
  },
  {
    id: "w4",
    word: "Diligent",
    wordClass: "Adjective",
    phonetic: "/ˈdɪlɪdʒənt/",
    translation: "ขยันหมั่นเพียร, ตั้งใจทำงาน",
    definitionEn:
      "Having or showing care and conscientiousness in one's work or duties.",
    definitionTh: "มีความใส่ใจและตั้งใจจริงในการทำงานหรือหน้าที่ของตน",
    exampleEn:
      "A diligent student will always review lessons before examinations.",
    exampleTh: "นักเรียนที่ขยันหมั่นเพียรจะทบทวนบทเรียนเสมอก่อนการสอบ",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story:
        'เสียงคล้าย "ดิลิ-เจ้นท์" -> ตัวเด่น (Gent) วิ่งทำงานรอบเตียงอย่าง "ขยันขันแข็ง"',
      keyword: "Gent (สุภาพบุรุษขยัน)",
    },
  },
  {
    id: "w5",
    word: "Evaluate",
    wordClass: "Verb",
    phonetic: "/ɪˈvæljueɪt/",
    translation: "ประเมินผล, ประเมินค่า",
    definitionEn: "Form an idea of the amount, number, or value of; assess.",
    definitionTh:
      "สร้างความคิดหรือวัดปริมาณ จำนวน หรือมูลค่าของสิ่งใดสิ่งหนึ่ง",
    exampleEn:
      "We need to evaluate the results of the marketing campaign before planning.",
    exampleTh: "เราจำเป็นต้องประเมินผลลัพธ์ของแคมเปญการตลาดก่อนวางแผนต่อ",
    difficulty: "Intermediate",
    category: "Business",
    mnemonic: {
      story:
        'เสียงคล้าย "อิ-แวล-ยู-เอท" -> คำว่า "Value" แปลว่า มูลค่า ใส่ "-ate" ทำเป็นกริยา แปลว่า "ประเมินค่า"',
      keyword: "Value (มูลค่า)",
    },
  },
  {
    id: "w6",
    word: "Frequent",
    wordClass: "Adjective",
    phonetic: "/ˈfriːkwənt/",
    translation: "บ่อยครั้ง, ถี่",
    definitionEn:
      "Occurring or done on many occasions with short intervals in between.",
    definitionTh: "เกิดขึ้นหรือกระทำหลายครั้งโดยมีช่วงเวลาสั้นๆ คั่นระหว่างกัน",
    exampleEn: "Heavy rain causes frequent floods in this low-lying area.",
    exampleTh: "ฝนที่ตกหนักทำให้เกิดน้ำท่วมบ่อยครั้งในพื้นที่ลุ่มต่ำแห่งนี้",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story:
        'คล้าย "ฟรี-ควีน" -> ได้คูปอง "ฟรี" บ่อยๆ จากพระราชินี (Queen) ทำให้ไปเที่ยว "บ่อยครั้ง"',
      keyword: "ฟรี + Queen",
    },
  },
  {
    id: "w7",
    word: "Gratitude",
    wordClass: "Noun",
    phonetic: "/ˈɡrætɪtuːd/",
    translation: "ความรู้สึกกตัญญู, ความรู้สึกขอบคุณ",
    definitionEn:
      "The quality of being thankful; readiness to show appreciation for and to return kindness.",
    definitionTh: "คุณค่าของการเป็นคนขอบคุณ รู้จักตระหนักและตอบแทนความเมตตา",
    exampleEn:
      "She expressed her deep gratitude to the doctors who saved her life.",
    exampleTh: "เธอแสดงความรู้สึกขอบคุณอย่างสุดซึ้งต่อคุณหมอที่ช่วยชีวิตเธอไว้",
    difficulty: "Beginner",
    category: "Emotion",
    mnemonic: {
      story:
        'คล้ายคำว่า "Great" (ดีมาก) ที่แสดงมารยาทที่ดีงาม คือการมี "ความกตัญญูและขอบคุณ"',
      keyword: "Great (ยอดเยี่ยม)",
    },
  },
  {
    id: "w8",
    word: "Happenstancе",
    wordClass: "Noun",
    phonetic: "/ˈhæpənstæns/",
    translation: "เรื่องบังเอิญ, ความบังเอิญ",
    definitionEn: "Coincidence; a chance situation or event.",
    definitionTh:
      "การเกิดขึ้นมาด้วยโชคชะตาหรือความบังเอิญ ไม่ได้ตั้งใจไว้เป๊ะๆ",
    exampleEn: "They met by pure happenstance at an airport in Tokyo.",
    exampleTh: "พวกเขาพบกันด้วยเรื่องบังเอิญอย่างแท้จริงที่สนามบินในโตเกียว",
    difficulty: "Advanced",
    category: "Travel",
    mnemonic: {
      story:
        'รวมคำว่า Happen (เกิดขึ้น) + Stance (ท่ายืน) -> การเกิดขึ้นมาในท่ายืนนั้นๆ ทันทีเป็น "เรื่องบังเอิญ"',
      keyword: "Happen (เกิด) + Stance (ท่ายืน)",
    },
  },
  {
    id: "w9",
    word: "Inevitable",
    wordClass: "Adjective",
    phonetic: "/ɪnˈevɪtəb(ə)l/",
    translation: "หลีกเลี่ยงไม่ได้, ต้องเกิดขึ้นแน่ๆ",
    definitionEn: "Certain to happen; unavoidable.",
    definitionTh: "แน่นอนที่จะเกิดขึ้น ไม่สามารถหลบเลี่ยงหรือป้องกันได้",
    exampleEn: "With so many cars on the road, traffic jams are inevitable.",
    exampleTh: "เมื่อรถเยอะมากบนถนน รถติดจึงเป็นสิ่งที่หลีกเลี่ยงไม่ได้",
    difficulty: "Advanced",
    category: "Daily Life",
    mnemonic: {
      story:
        'จำว่า "อิน-เอ-วิ-เทเบิล" -> นั่งโต๊ะอาหารอินเดีย (Table) ยังไงก็ต้องกินแป้งที่ "หลีกเลี่ยงไม่ได้"',
      keyword: "Table (โต๊ะเลี่ยงไม่ได้)",
    },
  },
  {
    id: "w10",
    word: "Jeopardy",
    wordClass: "Noun",
    phonetic: "/ˈdʒepərdi/",
    translation: "อันตราย, ความเสี่ยงต่อความสูญเสีย",
    definitionEn: "Danger of loss, harm, or failure.",
    definitionTh: "ภัยอันตรายที่อาจนำมาซึ่งความล้มเหลว สูญสิ้น หรือเสียหาย",
    exampleEn:
      "The company's financial crisis put hundreds of jobs in jeopardy.",
    exampleTh:
      "วิกฤตการเงินของบริษัททำให้งานคณบดีและลูกจ้างหลายร้อยคนตกอยู่ในอันตราย",
    difficulty: "Advanced",
    category: "Business",
    mnemonic: {
      story:
        'จำเสียง คล้าย "เจ็บ-พอดดี" -> ถ้าเดินตกหน้าผาจะ "เจ็บพอดี" เพราะทำเรื่อง "อันตรายและเสี่ยง"',
      keyword: "เจ็บพอดี (อันตราย)",
    },
  },
  {
    id: "w11",
    word: "Landscape",
    wordClass: "Noun",
    phonetic: "/ˈlændskeɪp/",
    translation: "ทิวทัศน์, ภูมิทัศน์",
    definitionEn:
      "All the visible features of an area of countryside or land, often considered in terms of their aesthetic appeal.",
    definitionTh:
      "ลักษณะภูมิประเทศที่มองเห็นได้กว้างไกล รวมถึงความสวยงามตามธรรมชาติ",
    exampleEn:
      "We stopped on top of the hill to enjoy the beautiful mountain landscape.",
    exampleTh: "พวกเราหยุดที่ยอดเขาเพื่อดื่มด่ำกับทิวทัศน์ภูเขาที่สวยงาม",
    difficulty: "Beginner",
    category: "Travel",
    mnemonic: {
      story:
        'คำว่า Land (แผ่นดิน) + scape (ฉาก) -> ฉากของแผ่นดินกว้างก็คือ "ทิวทัศน์"',
      keyword: "Land (แผ่นดิน) + Cape (แหลม/ฉาก)",
    },
  },
  {
    id: "w12",
    word: "Maintain",
    wordClass: "Verb",
    phonetic: "/meɪnˈteɪn/",
    translation: "รักษาไว้, บำรุงรักษา",
    definitionEn:
      "Cause or enable (a state or activity) to continue; keep in good condition.",
    definitionTh:
      "ทำให้สภาพเดิมหรือกิจกรรมเดิมดำเนินต่อไปได้, บำรุงรักษาให้อยู่ในสถานะที่ดี",
    exampleEn: "It is important to maintain a healthy study-life balance.",
    exampleTh:
      "มันเป็นสิ่งสำคัญมากที่จะรักษาสมดุลที่ดีระหว่างการเรียนและการชีวิต",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story:
        'จำว่า "เมน-เทน" -> เมนหลัก (Main) ต้องคอยคุ้มครองคน "สิบคน" (Ten) เพื่อ "รักษาความสงบไว้"',
      keyword: "Main (หลัก) + Ten (สิบ)",
    },
  },
  {
    id: "w13",
    word: "Negotiate",
    wordClass: "Verb",
    phonetic: "/nɪˈɡoʊʃieɪt/",
    translation: "เจรจาต่อรอง",
    definitionEn:
      "Try to reach an agreement or compromise by discussion with others.",
    definitionTh:
      "พยายามบรรลุข้อตกลงหรือประนีประนอมโดยผ่านการพูดคุยหารือกับผู้อื่น",
    exampleEn:
      "The two diplomats managed to negotiate a peace treaty successfully.",
    exampleTh: "นักการทูตทั้งสองสามารถเจรจาต่อรองสนธิสัญญาสันติภาพได้สำเร็จ",
    difficulty: "Intermediate",
    category: "Business",
    mnemonic: {
      story:
        'คล้าย "นิ-โก-เชียต" -> น้องนีจะโกอินเตอร์ เลยต้อง "เจรจาต่อรอง" เรื่องค่าตั๋วเป๊ะๆ',
      keyword: "นี + โก (ไป)",
    },
  },
  {
    id: "w14",
    word: "Obsolete",
    wordClass: "Adjective",
    phonetic: "/ˌɑːbsəˈliːt/",
    translation: "ล้าสมัย, ตกรุ่น",
    definitionEn: "No longer produced or used; out of date.",
    definitionTh: "ไม่มีการผลิตหรือปรับใช้อีกต่อไป, ตกยุค, ล้าสมัยมาก",
    exampleEn:
      "Floppy disks are obsolete and have been replaced by cloud storage.",
    exampleTh:
      "แผ่นฟลอปปีดิสก์นั้นล้าสมัยไปแล้วและถูกแทนที่ด้วยพื้นที่เก็บข้อมูลบนคลาวด์",
    difficulty: "Advanced",
    category: "Technology",
    mnemonic: {
      story:
        'จำคีย์ "อ๊อบ-โซ-ลีท" -> อ๊อบแอบกินซุปสลัดที่ต้มในหม้อสลัดดินเผาโบราณที่แสน "ล้าสมัย"',
      keyword: "หม้อดินโบราณ (ล้าสมัย)",
    },
  },
  {
    id: "w15",
    word: "Persuade",
    wordClass: "Verb",
    phonetic: "/pərˈsweɪd/",
    translation: "ชักชวน, โน้มน้าวใจ",
    definitionEn:
      "Provide a sound reason for someone to do something; convince.",
    definitionTh:
      "ให้เหตุผลที่ดีเพื่อให้บุคคลใดปฏิบัติบางสิ่งบางอย่าง, ชักจูงใจ, เล้าโลม",
    exampleEn:
      "I managed to persuade my parents to let me study abroad next semester.",
    exampleTh:
      "ฉันสามารถโน้มน้าวใจพ่อแม่ของฉันให้อนุญาตให้ฉันไปเรียนต่อต่างประเทศในภาคเรียนหน้าได้สำเร็จ",
    difficulty: "Intermediate",
    category: "Emotion",
    mnemonic: {
      story:
        'จำว่า "เพอร์-สเวด" -> ชวนเพื่อนว่า ใส่เสื้อเปียกเหงื่อ (Sweat) สีทอง "โน้มน้าว" ให้ไปออกกำลังกายสิ!',
      keyword: "Sweat (เหงื่อ)",
    },
  },
  {
    id: "w16",
    word: "Quench",
    wordClass: "Verb",
    phonetic: "/kwentʃ/",
    translation: "ดับกระหาย, ดับไฟ",
    definitionEn: "Satisfy one's thirst by drinking; extinguish a fire.",
    definitionTh: "ตอบสนองความกระหายด้วยการดื่มน้ำ หรือดับไฟ ดับความร้อน",
    exampleEn:
      "Nothing can quench your thirst on a hot day like a glass of cold water.",
    exampleTh:
      "ไม่มีอะไรจะช่วยดับกระหายของคุณในวันร้อนจัดได้ดีไปกว่าน้ำเย็นสักแก้ว",
    difficulty: "Advanced",
    category: "Travel",
    mnemonic: {
      story:
        'จำเสียง คล้าย "เควนช์" -> เสียงเวลาโยนก้อนหอนร้อนๆ ลงน้ำดัง "เคว้นนนช์!" เพื่อ "ดับไฟ/ดับความร้อน"',
      keyword: "ฉี่สสส! (โยนน้ำดับไฟ)",
    },
  },
  {
    id: "w17",
    word: "Resilient",
    wordClass: "Adjective",
    phonetic: "/rɪˈzɪliənt/",
    translation: "ยืดหยุ่น, ฟื้นตัวเร็ว, ล้มแล้วลุกไว",
    definitionEn:
      "Able to withstand or recover quickly from difficult conditions.",
    definitionTh: "สามารถทนทานหรือฟื้นตัวได้อย่างรวดเร็วจากสภาพวิกฤติต่างๆ",
    exampleEn:
      "Even after a disastrous earthquake, the resilient citizens rebuilt their town.",
    exampleTh:
      "แม้กระทั่งหลังแผ่นดินไหวร้ายแรง ชาวเมืองที่ล้มแล้วลุกไวก็ร่วมมือกันกู้เมืองกลับมา",
    difficulty: "Advanced",
    category: "Emotion",
    mnemonic: {
      story:
        'คล้าย "รี-ซิ-เลี่ยน" -> วิ่งสู้กับสิงโต (Lion) หลายรอบ (Re) บาดเจ็บแต่ก็ "ฟื้นตัวเร็วมาก"',
      keyword: "Re (ซ้ำ) + Lion (สิงโต)",
    },
  },
  {
    id: "w18",
    word: "Sufficient",
    wordClass: "Adjective",
    phonetic: "/səˈfɪʃnt/",
    translation: "เพียงพอ",
    definitionEn: "Enough; adequate.",
    definitionTh:
      "มีปริมาณที่พอดีกับความจำเป็น, ครบครันสำหรับวัตถุประสงค์หนึ่งๆ",
    exampleEn:
      "Make sure you have sufficient water and food before going on a trek.",
    exampleTh:
      "แต่งกายให้มั่นใจว่าคุณมีน้ำและอาหารที่เพียงพอก่อนที่จะออกเดินทางไกล",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story:
        'คล้ายคำว่า "ทรัพย์-ฟิเชียล" -> มีทรัพย์สมบัติ (Sub/Suf) ที่เพียงพอต่อการใช้ชีวิตอย่างสงบสุข',
      keyword: "ทรัพย์ (เงินทองเพียงพอ)",
    },
  },
  {
    id: "w19",
    word: "Terminate",
    wordClass: "Verb",
    phonetic: "/ˈtɜːrmɪneɪt/",
    translation: "ยุติ, ทำให้สิ้นสุด",
    definitionEn: "Bring to an end.",
    definitionTh: "ทำให้มาถึงจุดสิ้นสุด, ลงเอย, เลิกรา",
    exampleEn:
      "The contract will terminate automatically at the end of the year.",
    exampleTh: "สัญญาฉบับนี้จะสิ้นสุดลงโดยอัตโนมัติเมื่อถึงสิ้นปี",
    difficulty: "Intermediate",
    category: "Business",
    mnemonic: {
      story:
        'นึกถึงหนังเรื่อง "Terminator" (คนเหล็ก) ที่ได้รับมอบหมายภารกิจมาเพื่อ "ทำลายล้าง/ยุติ"',
      keyword: "Terminator (คนเหล็กทำลายล้าง)",
    },
  },
  {
    id: "w20",
    word: "Vivid",
    wordClass: "Adjective",
    phonetic: "/ˈvɪvɪd/",
    translation: "เจิดจ้า, ชัดเจน, มีชีวิตชีวา",
    definitionEn:
      "Producing powerful feelings or strong, clear images in the mind.",
    definitionTh:
      "แสดงสีสันเจิดจ้าแจ่มชัด หรือก่อให้เกิดจินตภาพหรือภาพความรู้สึกที่สดในสมอง",
    exampleEn:
      "I still have a vivid memory of my first trip to the ocean when I was five.",
    exampleTh:
      "ฉันยังคงมีความทรงจำที่ชัดเจนและมีชีวิตชีวาเกี่ยวกับการไปเที่ยวทะเลครั้งแรกตอนห้าขวบ",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story:
        'จำว่า "วิ-วิศ" -> เด็กชื่อวิวิศทำการวาดภาพสีน้ำได้ "ชัดเจนและมีชีวิตชีวามาก"',
      keyword: "วิวิศวาดภาพ",
    },
  },
  {
    id: "w21",
    word: "Adapt",
    wordClass: "Verb",
    phonetic: "/əˈdæpt/",
    translation: "ปรับตัว",
    definitionEn: "To change to suit different conditions.",
    definitionTh: "ปรับเปลี่ยนให้เข้ากับสภาพการณ์ที่แตกต่างออกไป",
    exampleEn: "You will have to adapt to the new working environment.",
    exampleTh: "คุณจะต้องปรับตัวให้เข้ากับสภาพแวดล้อมการทำงานใหม่",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: 'อะ-แดป -> อะ (a) แดป (tap) แตะเบาๆ เพื่อลอง "ปรับตัว" ให้คุ้นเคย',
      keyword: "แตะเบาๆ ปรับตัว",
    },
  },
  {
    id: "w22",
    word: "Benevolent",
    wordClass: "Adjective",
    phonetic: "/bəˈnevələnt/",
    translation: "ใจดี, มีเมตตา",
    definitionEn: "Well meaning and kindly.",
    definitionTh: "มีเจตนาดีและมีน้ำใจ",
    exampleEn:
      "He was a benevolent old man who helped everyone in the village.",
    exampleTh: "เขาเป็นชายชราที่มีเมตตาและช่วยเหลือทุกคนในหมู่บ้าน",
    difficulty: "Advanced",
    category: "Society",
    mnemonic: {
      story:
        "เบ-เน-โว-เลนท์ -> เบ็น (Ben) เป็นคนมีเมตตา เลนท์ (lent) ให้ยืมของเสมอ",
      keyword: "เบ็นใจดี",
    },
  },
  {
    id: "w23",
    word: "Conspicuous",
    wordClass: "Adjective",
    phonetic: "/kənˈspɪkjuəs/",
    translation: "สะดุดตา, เด่นชัด",
    definitionEn: "Standing out so as to be clearly visible.",
    definitionTh: "โดดเด่นออกมาจนมองเห็นได้ชัดเจน",
    exampleEn: "He made himself conspicuous by wearing a bright red hat.",
    exampleTh: "เขาทำให้ตัวเองสะดุดตาด้วยการสวมหมวกสีแดงสด",
    difficulty: "Advanced",
    category: "Daily Life",
    mnemonic: {
      story:
        'คอน-สปิค-คิว-อัส -> คอน (Con) สวมชุดดู "สะดุดตา" (Conspicuous) ยืนเด่นอยู่กลางงาน',
      keyword: "คอนแต่งตัวเด่น",
    },
  },
  {
    id: "w24",
    word: "Diligent",
    wordClass: "Adjective",
    phonetic: "/ˈdɪlɪdʒənt/",
    translation: "ขยันหมั่นเพียร",
    definitionEn:
      "Having or showing care and conscientiousness in one's work or duties.",
    definitionTh: "มีความใส่ใจและตั้งใจในงานหรือหน้าที่ของตน",
    exampleEn:
      "She was a diligent student who always finished her homework early.",
    exampleTh: "เธอเป็นนักเรียนที่ขยันและทำการบ้านเสร็จเร็วเสมอ",
    difficulty: "Intermediate",
    category: "Academic",
    mnemonic: {
      story:
        'ดิล-ลิ-เจ้นท์ -> ดิล (Dil) ขยันเหมือน "ดิน" ที่ค่อยๆ สร้างเป็นตึก',
      keyword: "ดินขยันสร้าง",
    },
  },
  {
    id: "w25",
    word: "Eager",
    wordClass: "Adjective",
    phonetic: "/ˈiːɡər/",
    translation: "กระตือรือร้น, อยากมาก",
    definitionEn: "Wanting to do or have something very much.",
    definitionTh: "ต้องการทำหรือมีบางสิ่งมาก",
    exampleEn: "The children were eager to open their presents.",
    exampleTh: "เด็กๆ ต่างกระตือรือร้นที่จะเปิดของขวัญของพวกเขา",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story:
        'อี-เกอร์ -> นึกถึง "อีกา" (Eager) ที่ "กระตือรือร้น" อยากกินอาหาร',
      keyword: "อีกากระตือรือร้น",
    },
  },
  {
    id: "w26",
    word: "Frugal",
    wordClass: "Adjective",
    phonetic: "/ˈfruːɡl/",
    translation: "ประหยัด, มัธยัสถ์",
    definitionEn: "Sparing or economical with regard to money or food.",
    definitionTh: "ประหยัดหรือใช้จ่ายอย่างคุ้มค่าในเรื่องเงินหรืออาหาร",
    exampleEn: "He lived a frugal life in a small cottage.",
    exampleTh: "เขาใช้ชีวิตอย่างประหยัดในกระท่อมหลังเล็ก",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story:
        'ฟรู-เกิล -> ฟังคล้าย "ฟู-กัล" -> ใช้เงินอย่าง "ฟูๆ" (ฟุ่มเฟือย) ไม่ได้ ต้อง "ประหยัด" (Frugal)',
      keyword: "ฟูไม่ได้ต้องประหยัด",
    },
  },
  {
    id: "w27",
    word: "Grateful",
    wordClass: "Adjective",
    phonetic: "/ˈɡreɪtfl/",
    translation: "รู้สึกขอบคุณ",
    definitionEn: "Feeling or showing an appreciation of kindness.",
    definitionTh: "รู้สึกหรือแสดงความซาบซึ้งในความเมตตา",
    exampleEn: "I am extremely grateful for all your help.",
    exampleTh: "ฉันรู้สึกขอบคุณเป็นอย่างยิ่งสำหรับความช่วยเหลือทั้งหมดของคุณ",
    difficulty: "Beginner",
    category: "Social",
    mnemonic: {
      story:
        'เกรท-ฟูล -> "เกรท" (Great) มากที่ "ฟูล" (Full) ไปด้วยใจที่ "ขอบคุณ"',
      keyword: "เกรท (เยี่ยม) ที่ขอบคุณ",
    },
  },
  {
    id: "w28",
    word: "Hectic",
    wordClass: "Adjective",
    phonetic: "/ˈhektɪk/",
    translation: "วุ่นวาย, ยุ่งเหยิง",
    definitionEn: "Full of incessant or frantic activity.",
    definitionTh: "เต็มไปด้วยกิจกรรมที่ไม่หยุดหย่อนหรือวุ่นวายโกลาหล",
    exampleEn: "We have had a hectic week at the office.",
    exampleTh: "เรามีสัปดาห์ที่วุ่นวายมากที่สำนักงาน",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story:
        'เฮค-ติค -> "เฮ้ย" (Hec) "ติ๊ก" (tic) เวลาผ่านไปเร็วมากจน "วุ่นวาย" ไปหมด',
      keyword: "เฮ้ยเวลาจะหมด",
    },
  },
  {
    id: "w29",
    word: "Immense",
    wordClass: "Adjective",
    phonetic: "/ɪˈmens/",
    translation: "ใหญ่โต, มหาศาล",
    definitionEn: "Extremely large or great, especially in scale or degree.",
    definitionTh: "ใหญ่หรือยิ่งใหญ่มาก โดยเฉพาะในแง่ของขนาดหรือระดับ",
    exampleEn: "The potential impact of this technology is immense.",
    exampleTh: "ผลกระทบที่เป็นไปได้ของเทคโนโลยีนี้มีมหาศาล",
    difficulty: "Intermediate",
    category: "Science",
    mnemonic: {
      story: 'อิม-เมนซ์ -> "อิ่ม" (Im) จน "เมน" (Men) ร่างกาย "ใหญ่โต มหาศาล"',
      keyword: "อิ่มจนตัวใหญ่",
    },
  },
  {
    id: "w30",
    word: "Jovial",
    wordClass: "Adjective",
    phonetic: "/ˈdʒəʊviəl/",
    translation: "ร่าเริง, สนุกสนาน",
    definitionEn: "Cheerful and friendly.",
    definitionTh: "ร่าเริงและเป็นมิตร",
    exampleEn: "She was in a jovial mood after the party.",
    exampleTh: "เธออยู่ในอารมณ์ที่ร่าเริงหลังจากงานเลี้ยง",
    difficulty: "Advanced",
    category: "Daily Life",
    mnemonic: {
      story:
        'โจ-เวียล -> นึกถึง "โจ" (Joe) ผู้ร่าเริง "เวียล" (Wheel) สนุกสนานไปทั่ว',
      keyword: "โจสนุกร่าเริง",
    },
  },
  {
    id: "w31",
    word: "Ambition",
    wordClass: "Noun",
    phonetic: "/æmˈbɪʃn/",
    translation: "ความทะเยอทะยาน",
    definitionEn: "A strong desire to do or to achieve something.",
    definitionTh: "ความปรารถนาอันแรงกล้าที่จะทำหรือบรรลุบางสิ่ง",
    exampleEn: "His ambition is to become a successful writer.",
    exampleTh: "ความทะเยอทะยานของเขาคือการเป็นนักเขียนที่ประสบความสำเร็จ",
    difficulty: "Intermediate",
    category: "Academic",
    mnemonic: {
      story:
        'แอม-บิ-ชั่น -> แอม (Am) บิ (bi) ชั่น (tion) คือความ "ทะเยอทะยาน" ของแอมที่จะเป็นใหญ่',
      keyword: "แอมทะเยอทะยาน",
    },
  },
  {
    id: "w32",
    word: "Brilliant",
    wordClass: "Adjective",
    phonetic: "/ˈbrɪljənt/",
    translation: "ฉลาดหลักแหลม, ยอดเยี่ยม",
    definitionEn: "Exceptionally clever or talented.",
    definitionTh: "ฉลาดหรือมีความสามารถเป็นพิเศษ",
    exampleEn: "She came up with a brilliant idea for the project.",
    exampleTh: "เธอเสนอความคิดที่ยอดเยี่ยมสำหรับโครงการนี้",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story:
        'บริล-เลียนท์ -> เหมือนเพชรที่ "เปล่งประกาย" สื่อถึงคน "ฉลาดหลักแหลม"',
      keyword: "เพชรประกาย",
    },
  },
  {
    id: "w33",
    word: "Compassion",
    wordClass: "Noun",
    phonetic: "/kəmˈpæʃn/",
    translation: "ความเห็นอกเห็นใจ, ความเมตตา",
    definitionEn:
      "Sympathetic pity and concern for the sufferings or misfortunes of others.",
    definitionTh: "ความสงสารและความห่วงใยในความทุกข์ยากของผู้อื่น",
    exampleEn: "He showed great compassion for the victims of the disaster.",
    exampleTh: "เขาแสดงความเห็นอกเห็นใจอย่างยิ่งต่อเหยื่อจากภัยพิบัติ",
    difficulty: "Intermediate",
    category: "Emotion",
    mnemonic: {
      story:
        'คัม-แพส-ชั่น -> "คัม" (Come) เข้ามาหาด้วย "ความเมตตา" (Compassion)',
      keyword: "เมตตาคัม (Come)",
    },
  },
  {
    id: "w34",
    word: "Durable",
    wordClass: "Adjective",
    phonetic: "/ˈdjʊərəbl/",
    translation: "ทนทาน",
    definitionEn: "Able to withstand wear, pressure, or damage; hard-wearing.",
    definitionTh: "สามารถทนต่อการสึกหรอ ความกดดัน หรือความเสียหาย",
    exampleEn: "The shoes are made of durable material.",
    exampleTh: "รองเท้าคู่นี้ทำมาจากวัสดุที่ทนทาน",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: 'ดู-รา-เบิล -> "ดู" (Du) สิ "รา" (ra) ทำของชิ้นนี้ได้ "ทนทาน" มาก',
      keyword: "ดูของทน",
    },
  },
  {
    id: "w35",
    word: "Eloquent",
    wordClass: "Adjective",
    phonetic: "/ˈeləkwənt/",
    translation: "พูดจาฉะฉาน, มีวาทศิลป์",
    definitionEn: "Fluent or persuasive in speaking or writing.",
    definitionTh: "ใช้คำพูดหรือการเขียนที่คล่องแคล่วหรือโน้มน้าวใจ",
    exampleEn: "He gave an eloquent speech that touched everyone.",
    exampleTh: "เขาให้คำปราศรัยที่ฉะฉานซึ่งจับใจทุกคน",
    difficulty: "Advanced",
    category: "Academic",
    mnemonic: {
      story:
        'เอล-โล-เควนท์ -> เอล (El) พูดจาฉะฉานมี "วาทศิลป์" (Eloquent) ดีเยี่ยม',
      keyword: "เอลพูดเก่ง",
    },
  },
  {
    id: "w36",
    word: "Fascinating",
    wordClass: "Adjective",
    phonetic: "/ˈfæsɪneɪtɪŋ/",
    translation: "น่าหลงใหล, น่าสนใจมาก",
    definitionEn: "Extremely interesting.",
    definitionTh: "น่าสนใจอย่างยิ่ง",
    exampleEn: "The museum has a fascinating collection of ancient artifacts.",
    exampleTh: "พิพิธภัณฑ์นี้มีคอลเลกชันวัตถุโบราณที่น่าหลงใหล",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: 'แฟส-ซิ-เน-ทิ่ง -> น่าหลงใหลจน "แฟส" (fast) ใจเต้นแรง',
      keyword: "น่าหลงใหล",
    },
  },
  {
    id: "w37",
    word: "Genuine",
    wordClass: "Adjective",
    phonetic: "/ˈdʒenjuɪn/",
    translation: "แท้, จริงใจ",
    definitionEn: "Truly what something is said to be; authentic.",
    definitionTh: "แท้จริง ไม่ได้เสแสร้ง",
    exampleEn: "She showed a genuine interest in helping others.",
    exampleTh: "เธอแสดงความสนใจอย่างจริงใจในการช่วยเหลือผู้อื่น",
    difficulty: "Intermediate",
    category: "Emotion",
    mnemonic: {
      story: 'เจน-ยู-อิน -> เจน (Jen) เป็นคน "จริงใจ" (Genuine) มาตั้งแต่เด็ก',
      keyword: "เจนคนจริง",
    },
  },
  {
    id: "w38",
    word: "Harmonious",
    wordClass: "Adjective",
    phonetic: "/hɑːrˈmoʊniəs/",
    translation: "กลมกลืน, ประสานกัน",
    definitionEn:
      "Tuneful; not discordant; forming a pleasing or consistent whole.",
    definitionTh: "ไพเราะ, ไม่ขัดแย้ง, สอดคล้องกัน",
    exampleEn: "The interior design creates a harmonious atmosphere.",
    exampleTh: "การออกแบบภายในสร้างบรรยากาศที่กลมกลืน",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story: 'ฮาร์-โม-นี-อัส -> เสียงเพลงที่ "ประสาน" (Harmonious) กันไพเราะ',
      keyword: "เพลงประสาน",
    },
  },
  {
    id: "w39",
    word: "Inspiring",
    wordClass: "Adjective",
    phonetic: "/ɪnˈspaɪərɪŋ/",
    translation: "เป็นแรงบันดาลใจ",
    definitionEn: "Having the effect of inspiring someone.",
    definitionTh: "ก่อให้เกิดแรงบันดาลใจ",
    exampleEn: "She is an inspiring leader who motivates her team.",
    exampleTh: "เธอเป็นผู้นำที่สร้างแรงบันดาลใจและกระตุ้นทีมของเธอ",
    difficulty: "Beginner",
    category: "Emotion",
    mnemonic: {
      story:
        'อิน-สปาย-ริ่ง -> ก่อให้เกิด "แรงบันดาลใจ" (Inspiring) ที่ยิ่งใหญ่',
      keyword: "แรงบันดาลใจ",
    },
  },
  {
    id: "w40",
    word: "Jubilant",
    wordClass: "Adjective",
    phonetic: "/ˈdʒuːbɪlənt/",
    translation: "ปิติยินดี, ร่าเริง",
    definitionEn: "Feeling or expressing great happiness and triumph.",
    definitionTh: "รู้สึกหรือแสดงความสุขอย่างยิ่งและชัยชนะ",
    exampleEn: "The fans were jubilant when their team won the championship.",
    exampleTh: "แฟนๆ ต่างปิติยินดีเมื่อทีมของพวกเขาชนะการแข่งขัน",
    difficulty: "Advanced",
    category: "Emotion",
    mnemonic: {
      story: 'จู-บิ-แลนท์ -> สุขจน "จู" (Ju) ตะโกนก้อง "ปิติยินดี" (Jubilant)',
      keyword: "ตะโกนสุข",
    },
  },
  {
    id: "w41",
    word: "Knowledgeable",
    wordClass: "Adjective",
    phonetic: "/ˈnɑːlɪdʒəbl/",
    translation: "มีความรู้ดี, รอบรู้",
    definitionEn: "Intelligent and well-informed.",
    definitionTh: "ฉลาดและมีความรู้ดี",
    exampleEn: "He is very knowledgeable about local history.",
    exampleTh: "เขาเป็นคนรอบรู้เกี่ยวกับประวัติศาสตร์ท้องถิ่นมาก",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story: 'นอ-เลด-จา-เบิล -> รู้ (Knowledge) มากจนใครๆ ก็ยอมรับว่า "รอบรู้"',
      keyword: "คนรอบรู้",
    },
  },
  {
    id: "w42",
    word: "Luminous",
    wordClass: "Adjective",
    phonetic: "/ˈluːmɪnəs/",
    translation: "สว่าง, สดใส",
    definitionEn: "Full of or shedding light; bright or shining.",
    definitionTh: "สว่างหรือเรืองแสง",
    exampleEn: "The moon cast a luminous glow over the lake.",
    exampleTh: "ดวงจันทร์ส่องแสงสว่างเหนือทะเลสาบ",
    difficulty: "Advanced",
    category: "Science",
    mnemonic: {
      story: 'ลู-มิ-นัส -> เหมือน "แสง" (Lum) ที่ "สว่าง" (Luminous) ในความมืด',
      keyword: "แสงสว่าง",
    },
  },
  {
    id: "w43",
    word: "Magnificent",
    wordClass: "Adjective",
    phonetic: "/mæɡˈnɪfɪsnt/",
    translation: "งดงาม, ยิ่งใหญ่",
    definitionEn: "Impressively beautiful, elaborate, or extravagant.",
    definitionTh: "สวยงามอลังการ",
    exampleEn: "The palace was a magnificent building.",
    exampleTh: "พระราชวังเป็นอาคารที่งดงามยิ่งใหญ่",
    difficulty: "Intermediate",
    category: "Travel",
    mnemonic: {
      story: 'แมก-นิ-ฟิ-เซนต์ -> งดงามจนน่า "ตื่นตะลึง" (Magnificent)',
      keyword: "งดงามอลังการ",
    },
  },
  {
    id: "w44",
    word: "Nurture",
    wordClass: "Verb",
    phonetic: "/ˈnɜːrtʃər/",
    translation: "ดูแลเอาใจใส่, บ่มเพาะ",
    definitionEn: "Care for and encourage the growth or development of.",
    definitionTh: "ดูแลและส่งเสริมการเจริญเติบโต",
    exampleEn: "She helped to nurture the talents of young musicians.",
    exampleTh: "เธอช่วยบ่มเพาะพรสวรรค์ของนักดนตรีหนุ่มสาว",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story:
        'เนอร์-เชอร์ -> เหมือนพยาบาล (Nurse) ที่คอย "ดูแลเอาใจใส่" (Nurture)',
      keyword: "พยาบาลดูแล",
    },
  },
  {
    id: "w45",
    word: "Optimistic",
    wordClass: "Adjective",
    phonetic: "/ˌɑːptɪˈmɪstɪk/",
    translation: "มองโลกในแง่ดี",
    definitionEn: "Hopeful and confident about the future.",
    definitionTh: "มีความหวังและมั่นใจเกี่ยวกับอนาคต",
    exampleEn: "She remained optimistic despite all the challenges.",
    exampleTh: "เธอยังคงมองโลกในแง่ดีแม้จะมีความท้าทายทั้งหมด",
    difficulty: "Beginner",
    category: "Emotion",
    mnemonic: {
      story:
        'ออป-ติ-มิส-ติค -> คนที่มอง (Opti) ทุกอย่างเป็นบวก (Positive) คือคน "มองโลกในแง่ดี"',
      keyword: "มองบวก",
    },
  },
  {
    id: "w46",
    word: "Persevere",
    wordClass: "Verb",
    phonetic: "/ˌpɜːrsəˈvɪr/",
    translation: "มุ่งมั่น, พยายามไม่ย่อท้อ",
    definitionEn:
      "Continue in a course of action even in the face of difficulty.",
    definitionTh: "ทำต่อไปแม้จะเผชิญกับความยากลำบาก",
    exampleEn: "You have to persevere if you want to achieve your goals.",
    exampleTh: "คุณต้องมุ่งมั่นถ้าคุณต้องการบรรลุเป้าหมายของคุณ",
    difficulty: "Advanced",
    category: "Academic",
    mnemonic: {
      story: 'เพอร์-เซ-เวียร์ -> "มุ่งมั่น" (Persevere) จน "เห็นผล" (See)',
      keyword: "มุ่งมั่นทำต่อ",
    },
  },
  {
    id: "w47",
    word: "Quality",
    wordClass: "Noun",
    phonetic: "/ˈkwɑːləti/",
    translation: "คุณภาพ, คุณสมบัติ",
    definitionEn: "The standard of something as measured against other things.",
    definitionTh: "มาตรฐานของสิ่งของ",
    exampleEn: "We are committed to providing high-quality service.",
    exampleTh: "เรามุ่งมั่นที่จะให้บริการที่มีคุณภาพสูง",
    difficulty: "Beginner",
    category: "Business",
    mnemonic: {
      story: 'ควอ-ลิ-ตี้ -> มาตรฐาน (Standard) สูงคือ "คุณภาพ"',
      keyword: "คุณภาพ",
    },
  },
  {
    id: "w48",
    word: "Radiant",
    wordClass: "Adjective",
    phonetic: "/ˈreɪdiənt/",
    translation: "เปล่งประกาย, สดใส",
    definitionEn: "Sending out light; shining or glowing brightly.",
    definitionTh: "ส่องแสงสว่าง",
    exampleEn: "She looked radiant in her wedding dress.",
    exampleTh: "เธอดูเปล่งประกายในชุดแต่งงานของเธอ",
    difficulty: "Intermediate",
    category: "Daily Life",
    mnemonic: {
      story: 'เร-เดียนท์ -> "เปล่งประกาย" (Radiant) เหมือนแสงอาทิตย์ยามเช้า',
      keyword: "เปล่งประกาย",
    },
  },
  {
    id: "w49",
    word: "Sincere",
    wordClass: "Adjective",
    phonetic: "/sɪnˈsɪr/",
    translation: "จริงใจ",
    definitionEn:
      "Free from pretense or deceit; proceeding from genuine feelings.",
    definitionTh: "ปราศจากการเสแสร้ง",
    exampleEn: "He offered his sincere apologies for the mistake.",
    exampleTh: 'เขาเสนอคำขอโทษที่ "จริงใจ" สำหรับความผิดพลาดนั้น',
    difficulty: "Beginner",
    category: "Emotion",
    mnemonic: {
      story: 'ซิน-เซียร์ -> "จริงใจ" (Sincere) ในแบบที่ใครๆ ก็เชื่อ',
      keyword: "จริงใจสุดๆ",
    },
  },
  {
    id: "w50",
    word: "Triumph",
    wordClass: "Noun",
    phonetic: "/ˈtraɪʌmf/",
    translation: "ชัยชนะ, ความสำเร็จอันยิ่งใหญ่",
    definitionEn: "A great victory or achievement.",
    definitionTh: "ชัยชนะหรือความสำเร็จที่ยอดเยี่ยม",
    exampleEn: "The team celebrated their triumph after the game.",
    exampleTh: "ทีมฉลองชัยชนะหลังจากจบเกม",
    difficulty: "Intermediate",
    category: "Society",
    mnemonic: {
      story: 'ซิน-เซียร์ -> "จริงใจ" (Sincere) ในแบบที่ใครๆ ก็เชื่อ',
      keyword: "จริงใจสุดๆ",
    },
  },
  {
    id: "w51",
    word: "Apple",
    wordClass: "Noun",
    phonetic: "/ˈæpl/",
    translation: "แอปเปิล",
    definitionEn: "A round fruit with red, yellow, or green skin.",
    definitionTh: "ผลไม้ทรงกลมที่มีผิวสีแดง เหลือง หรือเขียว",
    exampleEn: "I eat an apple every day.",
    exampleTh: "ฉันกินแอปเปิลทุกวัน",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "แอปเปิลลูกแดงน่ากิน",
      keyword: "ผลไม้",
    },
  },
  {
    id: "w52",
    word: "Banana",
    wordClass: "Noun",
    phonetic: "/bəˈnænə/",
    translation: "กล้วย",
    definitionEn: "A long, curved fruit with a yellow skin.",
    definitionTh: "ผลไม้รูปทรงยาว โค้งงอ มีผิวสีเหลือง",
    exampleEn: "Monkeys love bananas.",
    exampleTh: "ลิงชอบกินกล้วย",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "กล้วยสีเหลืองอร่าม",
      keyword: "กล้วย",
    },
  },
  {
    id: "w53",
    word: "Cat",
    wordClass: "Noun",
    phonetic: "/kæt/",
    translation: "แมว",
    definitionEn: "A small, furry animal often kept as a pet.",
    definitionTh: "สัตว์ตัวเล็กมีขนมักถูกเลี้ยงไว้เป็นสัตว์เลี้ยง",
    exampleEn: "The cat is sleeping on the sofa.",
    exampleTh: "แมวกำลังนอนอยู่บนโซฟา",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "แมวเหมียวร้องเรียกเมี๊ยว",
      keyword: "แมว",
    },
  },
  {
    id: "w54",
    word: "Dog",
    wordClass: "Noun",
    phonetic: "/dɒɡ/",
    translation: "สุนัข",
    definitionEn: "A common four-legged animal, often a pet.",
    definitionTh: "สัตว์สี่ขาทั่วไป มักเป็นสัตว์เลี้ยง",
    exampleEn: "The dog is barking at the stranger.",
    exampleTh: "สุนัขกำลังเห่าคนแปลกหน้า",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "สุนัขแสนซื่อสัตย์",
      keyword: "สุนัข",
    },
  },
  {
    id: "w55",
    word: "Egg",
    wordClass: "Noun",
    phonetic: "/eɡ/",
    translation: "ไข่",
    definitionEn: "The oval object laid by a female bird.",
    definitionTh: "วัตถุรูปไข่ที่นกตัวเมียวางไข่",
    exampleEn: "I like boiled eggs for breakfast.",
    exampleTh: "ฉันชอบกินไข่ต้มเป็นอาหารเช้า",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ไข่ไก่ฟองกลม",
      keyword: "ไข่",
    },
  },
  {
    id: "w56",
    word: "Fish",
    wordClass: "Noun",
    phonetic: "/fɪʃ/",
    translation: "ปลา",
    definitionEn: "An animal that lives in water and has gills.",
    definitionTh: "สัตว์ที่อาศัยอยู่ในน้ำและมีเหงือก",
    exampleEn: "There are many colorful fish in the aquarium.",
    exampleTh: "มีปลาที่มีสีสันมากมายในตู้ปลา",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ปลาว่ายน้ำไปมา",
      keyword: "ปลา",
    },
  },
  {
    id: "w57",
    word: "Goat",
    wordClass: "Noun",
    phonetic: "/ɡoʊt/",
    translation: "แพะ",
    definitionEn: "A small animal with horns and a beard.",
    definitionTh: "สัตว์ตัวเล็กที่มีเขางอกและมีเครา",
    exampleEn: "The goat is eating grass.",
    exampleTh: "แพะกำลังกินหญ้า",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "แพะร้องแบะแบะ",
      keyword: "แพะ",
    },
  },
  {
    id: "w58",
    word: "Hat",
    wordClass: "Noun",
    phonetic: "/hæt/",
    translation: "หมวก",
    definitionEn: "A covering for the head.",
    definitionTh: "สิ่งที่ใช้สำหรับสวมศีรษะ",
    exampleEn: "She wears a hat in the sun.",
    exampleTh: "เธอสวมหมวกกลางแดด",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "หมวกช่วยบังแดด",
      keyword: "หมวก",
    },
  },
  {
    id: "w59",
    word: "Ink",
    wordClass: "Noun",
    phonetic: "/ɪŋk/",
    translation: "หมึก",
    definitionEn: "A colored liquid used for writing or printing.",
    definitionTh: "ของเหลวที่มีสีใช้สำหรับเขียนหรือพิมพ์",
    exampleEn: "The pen is out of ink.",
    exampleTh: "ปากกาหมึกหมดแล้ว",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story: "หมึกสีดำเขียนง่าย",
      keyword: "หมึก",
    },
  },
  {
    id: "w60",
    word: "Jam",
    wordClass: "Noun",
    phonetic: "/dʒæm/",
    translation: "แยม",
    definitionEn: "A sweet food made from fruit and sugar.",
    definitionTh: "อาหารหวานทำจากผลไม้และน้ำตาล",
    exampleEn: "I spread strawberry jam on my toast.",
    exampleTh: "ฉันทาแยมสตรอว์เบอร์รีบนขนมปังปิ้ง",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "แยมผลไม้รสหวาน",
      keyword: "แยม",
    },
  },
  {
    id: "w61",
    word: "Key",
    wordClass: "Noun",
    phonetic: "/kiː/",
    translation: "กุญแจ",
    definitionEn: "A small metal piece for opening a lock.",
    definitionTh: "ชิ้นส่วนโลหะขนาดเล็กสำหรับเปิดแม่กุญแจ",
    exampleEn: "I lost my keys.",
    exampleTh: "ฉันทำกุญแจหาย",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "กุญแจไขประตู",
      keyword: "กุญแจ",
    },
  },
  {
    id: "w62",
    word: "Lamp",
    wordClass: "Noun",
    phonetic: "/læmp/",
    translation: "โคมไฟ",
    definitionEn: "A device for giving light.",
    definitionTh: "อุปกรณ์สำหรับให้แสงสว่าง",
    exampleEn: "She turned on the lamp.",
    exampleTh: "เธอเปิดโคมไฟ",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "โคมไฟส่องสว่าง",
      keyword: "โคมไฟ",
    },
  },
  {
    id: "w63",
    word: "Milk",
    wordClass: "Noun",
    phonetic: "/mɪlk/",
    translation: "นม",
    definitionEn: "A white liquid produced by mammals.",
    definitionTh: "ของเหลวสีขาวที่ผลิตโดยสัตว์เลี้ยงลูกด้วยนม",
    exampleEn: "Children should drink milk.",
    exampleTh: "เด็กๆ ควรดื่มนม",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "นมมีประโยชน์",
      keyword: "นม",
    },
  },
  {
    id: "w64",
    word: "Net",
    wordClass: "Noun",
    phonetic: "/net/",
    translation: "ตาข่าย",
    definitionEn: "A mesh for catching fish or insects.",
    definitionTh: "ตาข่ายสำหรับจับปลาหรือแมลง",
    exampleEn: "The fisherman used a net.",
    exampleTh: "ชาวประมงใช้ตาข่าย",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ตาข่ายจับปลา",
      keyword: "ตาข่าย",
    },
  },
  {
    id: "w65",
    word: "Owl",
    wordClass: "Noun",
    phonetic: "/aʊl/",
    translation: "นกฮูก",
    definitionEn: "A bird that hunts at night.",
    definitionTh: "นกที่ล่าเหยื่อในตอนกลางคืน",
    exampleEn: "The owl hooted in the night.",
    exampleTh: "นกฮูกร้องในตอนกลางคืน",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "นกฮูกตาโต",
      keyword: "นกฮูก",
    },
  },
  {
    id: "w66",
    word: "Pen",
    wordClass: "Noun",
    phonetic: "/pen/",
    translation: "ปากกา",
    definitionEn: "A tool for writing with ink.",
    definitionTh: "อุปกรณ์สำหรับเขียนด้วยหมึก",
    exampleEn: "He wrote with a pen.",
    exampleTh: "เขาเขียนด้วยปากกา",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story: "ปากกาเขียนหนังสือ",
      keyword: "ปากกา",
    },
  },
  {
    id: "w67",
    word: "Quilt",
    wordClass: "Noun",
    phonetic: "/kwɪlt/",
    translation: "ผ้าห่ม",
    definitionEn: "A warm cover for a bed.",
    definitionTh: "ผ้าคลุมที่ให้ความอบอุ่นสำหรับเตียง",
    exampleEn: "The quilt kept me warm.",
    exampleTh: "ผ้าห่มทำให้ฉันอบอุ่น",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ผ้าห่มนุ่มนิ่ม",
      keyword: "ผ้าห่ม",
    },
  },
  {
    id: "w68",
    word: "Rat",
    wordClass: "Noun",
    phonetic: "/ræt/",
    translation: "หนู",
    definitionEn: "A small rodent.",
    definitionTh: "สัตว์ฟันแทะขนาดเล็ก",
    exampleEn: "The rat ran away.",
    exampleTh: "หนูวิ่งหนีไป",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "หนูตัวเล็ก",
      keyword: "หนู",
    },
  },
  {
    id: "w69",
    word: "Sun",
    wordClass: "Noun",
    phonetic: "/sʌn/",
    translation: "ดวงอาทิตย์",
    definitionEn: "The star around which the earth orbits.",
    definitionTh: "ดาวฤกษ์ที่โลกโคจรรอบ",
    exampleEn: "The sun is very hot.",
    exampleTh: "ดวงอาทิตย์ร้อนมาก",
    difficulty: "Beginner",
    category: "Science",
    mnemonic: {
      story: "ดวงอาทิตย์ส่องแสง",
      keyword: "ดวงอาทิตย์",
    },
  },
  {
    id: "w70",
    word: "Tea",
    wordClass: "Noun",
    phonetic: "/tiː/",
    translation: "ชา",
    definitionEn: "A drink made by infusing tea leaves.",
    definitionTh: "เครื่องดื่มที่ทำจากใบชา",
    exampleEn: "She drinks tea every morning.",
    exampleTh: "เธอดื่มชาทุกเช้า",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ชาหอมกรุ่น",
      keyword: "ชา",
    },
  },
  {
    id: "w71",
    word: "Umbrella",
    wordClass: "Noun",
    phonetic: "/ʌmˈbrelə/",
    translation: "ร่ม",
    definitionEn: "A device used for protection against rain or sun.",
    definitionTh: "อุปกรณ์ที่ใช้ป้องกันฝนหรือแดด",
    exampleEn: "Take an umbrella, it might rain.",
    exampleTh: "เอาร่มไปด้วย เผื่อฝนตก",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ร่มกันฝนตกเปียก",
      keyword: "ร่ม",
    },
  },
  {
    id: "w72",
    word: "Van",
    wordClass: "Noun",
    phonetic: "/væn/",
    translation: "รถตู้",
    definitionEn: "A vehicle for carrying goods or people.",
    definitionTh: "ยานพาหนะสำหรับบรรทุกสินค้าหรือผู้คน",
    exampleEn: "We traveled by van.",
    exampleTh: "เราเดินทางด้วยรถตู้",
    difficulty: "Beginner",
    category: "Travel",
    mnemonic: {
      story: "รถตู้คันใหญ่",
      keyword: "รถตู้",
    },
  },
  {
    id: "w73",
    word: "Watch",
    wordClass: "Noun",
    phonetic: "/wɒtʃ/",
    translation: "นาฬิกาข้อมือ",
    definitionEn: "A small timepiece worn on the wrist.",
    definitionTh: "เครื่องบอกเวลาขนาดเล็กที่สวมบนข้อมือ",
    exampleEn: "I check my watch.",
    exampleTh: "ฉันดูนาฬิกาข้อมือของฉัน",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ดูเวลาที่ข้อมือ",
      keyword: "นาฬิกา",
    },
  },
  {
    id: "w74",
    word: "Xylophone",
    wordClass: "Noun",
    phonetic: "/ˈzaɪləfoʊn/",
    translation: "ระนาด",
    definitionEn: "A musical instrument played by striking bars.",
    definitionTh: "เครื่องดนตรีที่เล่นโดยการตีแท่งเสียง",
    exampleEn: "She plays the xylophone.",
    exampleTh: "เธอเล่นระนาด",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story: "ระนาดเสียงเพราะ",
      keyword: "ดนตรี",
    },
  },
  {
    id: "w75",
    word: "Yarn",
    wordClass: "Noun",
    phonetic: "/jɑːrn/",
    translation: "เส้นด้าย",
    definitionEn: "Spun thread used for knitting or weaving.",
    definitionTh: "เส้นด้ายที่ปั่นไว้สำหรับถักหรือทอ",
    exampleEn: "She is knitting with yarn.",
    exampleTh: "เธอกำลังถักด้วยเส้นด้าย",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ด้ายเส้นยาว",
      keyword: "ด้าย",
    },
  },
  {
    id: "w76",
    word: "Zoo",
    wordClass: "Noun",
    phonetic: "/zuː/",
    translation: "สวนสัตว์",
    definitionEn: "A place where animals are kept for public display.",
    definitionTh: "สถานที่ที่เก็บรวบรวมสัตว์ไว้เพื่อแสดงให้สาธารณะชม",
    exampleEn: "We visited the zoo.",
    exampleTh: "เราไปเที่ยวสวนสัตว์",
    difficulty: "Beginner",
    category: "Travel",
    mnemonic: {
      story: "สวนสัตว์มีสัตว์มากมาย",
      keyword: "สัตว์",
    },
  },
  {
    id: "w77",
    word: "Book",
    wordClass: "Noun",
    phonetic: "/bʊk/",
    translation: "หนังสือ",
    definitionEn: "A set of pages used for reading.",
    definitionTh: "ชุดของหน้าที่ใช้สำหรับการอ่าน",
    exampleEn: "I love reading books.",
    exampleTh: "ฉันชอบอ่านหนังสือ",
    difficulty: "Beginner",
    category: "Academic",
    mnemonic: {
      story: "อ่านหนังสือได้ความรู้",
      keyword: "หนังสือ",
    },
  },
  {
    id: "w78",
    word: "Chair",
    wordClass: "Noun",
    phonetic: "/tʃeər/",
    translation: "เก้าอี้",
    definitionEn: "A seat for one person.",
    definitionTh: "ที่นั่งสำหรับหนึ่งคน",
    exampleEn: "Sit on the chair.",
    exampleTh: "นั่งบนเก้าอี้",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "เก้าอี้นั่งสบาย",
      keyword: "เก้าอี้",
    },
  },
  {
    id: "w79",
    word: "Desk",
    wordClass: "Noun",
    phonetic: "/desk/",
    translation: "โต๊ะทำงาน",
    definitionEn: "A table used for working.",
    definitionTh: "โต๊ะที่ใช้สำหรับการทำงาน",
    exampleEn: "My computer is on the desk.",
    exampleTh: "คอมพิวเตอร์ของฉันอยู่บนโต๊ะทำงาน",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "โต๊ะสำหรับทำงาน",
      keyword: "โต๊ะ",
    },
  },
  {
    id: "w80",
    word: "Ear",
    wordClass: "Noun",
    phonetic: "/ɪər/",
    translation: "หู",
    definitionEn: "The organ of hearing.",
    definitionTh: "อวัยวะสำหรับการได้ยิน",
    exampleEn: "I have two ears.",
    exampleTh: "ฉันมีหูสองข้าง",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "หูไว้ฟังเสียง",
      keyword: "อวัยวะ",
    },
  },
  {
    id: "w81",
    word: "Fan",
    wordClass: "Noun",
    phonetic: "/fæn/",
    translation: "พัดลม",
    definitionEn: "A machine for creating a breeze.",
    definitionTh: "เครื่องจักรสำหรับสร้างลม",
    exampleEn: "Turn on the fan.",
    exampleTh: "เปิดพัดลม",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "พัดลมช่วยคลายร้อน",
      keyword: "พัดลม",
    },
  },
  {
    id: "w82",
    word: "Gate",
    wordClass: "Noun",
    phonetic: "/ɡeɪt/",
    translation: "ประตูรั้ว",
    definitionEn: "A door in a fence or wall.",
    definitionTh: "ประตูในรั้วหรือกำแพง",
    exampleEn: "Close the gate.",
    exampleTh: "ปิดประตูรั้ว",
    difficulty: "Beginner",
    category: "Daily Life",
    mnemonic: {
      story: "ประตูรั้วบ้าน",
      keyword: "ประตู",
    },
  },
  {
    id: 'w83',
    word: 'Hand',
    wordClass: 'Noun',
    phonetic: '/hænd/',
    translation: 'มือ',
    definitionEn: 'The end part of the arm.',
    definitionTh: 'ส่วนปลายของแขน',
    exampleEn: 'Wash your hands.',
    exampleTh: 'ล้างมือของคุณ',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'มือมีห้านิ้ว',
      keyword: 'อวัยวะ'
    }
  },
  {
    id: 'w84',
    word: 'Ice',
    wordClass: 'Noun',
    phonetic: '/aɪs/',
    translation: 'น้ำแข็ง',
    definitionEn: 'Frozen water.',
    definitionTh: 'น้ำที่แข็งตัว',
    exampleEn: 'I want ice in my drink.',
    exampleTh: 'ฉันอยากได้น้ำแข็งในเครื่องดื่ม',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'น้ำแข็งเย็นเจี๊ยบ',
      keyword: 'น้ำแข็ง'
    }
  },
  {
    id: 'w85',
    word: 'Jar',
    wordClass: 'Noun',
    phonetic: '/dʒɑːr/',
    translation: 'ขวดโหล',
    definitionEn: 'A wide-mouthed container.',
    definitionTh: 'ภาชนะปากกว้าง',
    exampleEn: 'A jar of cookies.',
    exampleTh: 'ขวดโหลใส่คุกกี้',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'โหลใส่ของ',
      keyword: 'ภาชนะ'
    }
  },
  {
    id: 'w86',
    word: 'Kite',
    wordClass: 'Noun',
    phonetic: '/kaɪt/',
    translation: 'ว่าว',
    definitionEn: 'A toy flown in the wind.',
    definitionTh: 'ของเล่นที่บินได้ในลม',
    exampleEn: 'I fly a kite.',
    exampleTh: 'ฉันเล่นว่าว',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'ว่าวบินบนฟ้า',
      keyword: 'ของเล่น'
    }
  },
  {
    id: 'w87',
    word: 'Leaf',
    wordClass: 'Noun',
    phonetic: '/liːf/',
    translation: 'ใบไม้',
    definitionEn: 'A green part of a plant.',
    definitionTh: 'ส่วนสีเขียวของพืช',
    exampleEn: 'The leaf is green.',
    exampleTh: 'ใบไม้สีเขียว',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'ใบไม้ร่วง',
      keyword: 'พืช'
    }
  },
  {
    id: 'w88',
    word: 'Moon',
    wordClass: 'Noun',
    phonetic: '/muːn/',
    translation: 'ดวงจันทร์',
    definitionEn: 'A natural satellite of the earth.',
    definitionTh: 'ดาวบริวารธรรมชาติของโลก',
    exampleEn: 'The moon is bright.',
    exampleTh: 'ดวงจันทร์สว่าง',
    difficulty: 'Beginner',
    category: 'Science',
    mnemonic: {
      story: 'พระจันทร์ตอนกลางคืน',
      keyword: 'ดวงจันทร์'
    }
  },
  {
    id: 'w89',
    word: 'Nut',
    wordClass: 'Noun',
    phonetic: '/nʌt/',
    translation: 'ถั่ว',
    definitionEn: 'A hard-shelled fruit.',
    definitionTh: 'ผลไม้ที่มีเปลือกแข็ง',
    exampleEn: 'I like to eat nuts.',
    exampleTh: 'ฉันชอบกินถั่ว',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'ถั่วกรุบกรอบ',
      keyword: 'อาหาร'
    }
  },
  {
    id: 'w90',
    word: 'Oil',
    wordClass: 'Noun',
    phonetic: '/ɔɪl/',
    translation: 'น้ำมัน',
    definitionEn: 'A viscous liquid.',
    definitionTh: 'ของเหลวที่มีความหนืด',
    exampleEn: 'Use some cooking oil.',
    exampleTh: 'ใช้น้ำมันทำอาหาร',
    difficulty: 'Beginner',
    category: 'Daily Life',
    mnemonic: {
      story: 'น้ำมันใช้ทอด',
      keyword: 'น้ำมัน'
    }
  }
];

